/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PatientsIndexRouteImport } from './routes/patients.index'
import { Route as PatientsNewRouteImport } from './routes/patients.new'
import { Route as PatientsIdRouteImport } from './routes/patients.$id'
import { Route as ApiFhirSplatRouteImport } from './routes/api/fhir.$'

const PatientsIndexRoute = PatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsNewRoute = PatientsNewRouteImport.update({
  id: '/patients/new',
  path: '/patients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIdRoute = PatientsIdRouteImport.update({
  id: '/patients/$id',
  path: '/patients/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFhirSplatRoute = ApiFhirSplatRouteImport.update({
  id: '/api/fhir/$',
  path: '/api/fhir/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/patients/$id': typeof PatientsIdRoute
  '/patients/new': typeof PatientsNewRoute
  '/patients/': typeof PatientsIndexRoute
  '/api/fhir/$': typeof ApiFhirSplatRoute
}
export interface FileRoutesByTo {
  '/patients/$id': typeof PatientsIdRoute
  '/patients/new': typeof PatientsNewRoute
  '/patients': typeof PatientsIndexRoute
  '/api/fhir/$': typeof ApiFhirSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/patients/$id': typeof PatientsIdRoute
  '/patients/new': typeof PatientsNewRoute
  '/patients/': typeof PatientsIndexRoute
  '/api/fhir/$': typeof ApiFhirSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/patients/$id' | '/patients/new' | '/patients/' | '/api/fhir/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/patients/$id' | '/patients/new' | '/patients' | '/api/fhir/$'
  id:
    | '__root__'
    | '/patients/$id'
    | '/patients/new'
    | '/patients/'
    | '/api/fhir/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PatientsIdRoute: typeof PatientsIdRoute
  PatientsNewRoute: typeof PatientsNewRoute
  PatientsIndexRoute: typeof PatientsIndexRoute
  ApiFhirSplatRoute: typeof ApiFhirSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/patients/': {
      id: '/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof PatientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/new': {
      id: '/patients/new'
      path: '/patients/new'
      fullPath: '/patients/new'
      preLoaderRoute: typeof PatientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$id': {
      id: '/patients/$id'
      path: '/patients/$id'
      fullPath: '/patients/$id'
      preLoaderRoute: typeof PatientsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fhir/$': {
      id: '/api/fhir/$'
      path: '/api/fhir/$'
      fullPath: '/api/fhir/$'
      preLoaderRoute: typeof ApiFhirSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  PatientsIdRoute: PatientsIdRoute,
  PatientsNewRoute: PatientsNewRoute,
  PatientsIndexRoute: PatientsIndexRoute,
  ApiFhirSplatRoute: ApiFhirSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
