/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientsNewRouteImport } from './routes/patients.new'
import { Route as PatientsIdRouteImport } from './routes/patients.$id'
import { Route as ApiFhirSplatRouteImport } from './routes/api/fhir.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsNewRoute = PatientsNewRouteImport.update({
  id: '/patients/new',
  path: '/patients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIdRoute = PatientsIdRouteImport.update({
  id: '/patients/$id',
  path: '/patients/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFhirSplatRoute = ApiFhirSplatRouteImport.update({
  id: '/api/fhir/$',
  path: '/api/fhir/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/patients/$id': typeof PatientsIdRoute
  '/patients/new': typeof PatientsNewRoute
  '/api/fhir/$': typeof ApiFhirSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/patients/$id': typeof PatientsIdRoute
  '/patients/new': typeof PatientsNewRoute
  '/api/fhir/$': typeof ApiFhirSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/patients/$id': typeof PatientsIdRoute
  '/patients/new': typeof PatientsNewRoute
  '/api/fhir/$': typeof ApiFhirSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/patients/$id' | '/patients/new' | '/api/fhir/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/patients/$id' | '/patients/new' | '/api/fhir/$'
  id: '__root__' | '/' | '/patients/$id' | '/patients/new' | '/api/fhir/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PatientsIdRoute: typeof PatientsIdRoute
  PatientsNewRoute: typeof PatientsNewRoute
  ApiFhirSplatRoute: typeof ApiFhirSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/new': {
      id: '/patients/new'
      path: '/patients/new'
      fullPath: '/patients/new'
      preLoaderRoute: typeof PatientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$id': {
      id: '/patients/$id'
      path: '/patients/$id'
      fullPath: '/patients/$id'
      preLoaderRoute: typeof PatientsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fhir/$': {
      id: '/api/fhir/$'
      path: '/api/fhir/$'
      fullPath: '/api/fhir/$'
      preLoaderRoute: typeof ApiFhirSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PatientsIdRoute: PatientsIdRoute,
  PatientsNewRoute: PatientsNewRoute,
  ApiFhirSplatRoute: ApiFhirSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
