/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FhirResourcesRouteImport } from './routes/fhir-resources'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientsIndexRouteImport } from './routes/patients.index'
import { Route as PatientsNewRouteImport } from './routes/patients.new'
import { Route as PatientsIdRouteImport } from './routes/patients.$id'
import { Route as DashboardPhysicianRouteImport } from './routes/dashboard.physician'
import { Route as DashboardFrontOfficeRouteImport } from './routes/dashboard.front-office'
import { Route as ApiFhirSplatRouteImport } from './routes/api/fhir.$'

const FhirResourcesRoute = FhirResourcesRouteImport.update({
  id: '/fhir-resources',
  path: '/fhir-resources',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIndexRoute = PatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsNewRoute = PatientsNewRouteImport.update({
  id: '/patients/new',
  path: '/patients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIdRoute = PatientsIdRouteImport.update({
  id: '/patients/$id',
  path: '/patients/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPhysicianRoute = DashboardPhysicianRouteImport.update({
  id: '/dashboard/physician',
  path: '/dashboard/physician',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFrontOfficeRoute = DashboardFrontOfficeRouteImport.update({
  id: '/dashboard/front-office',
  path: '/dashboard/front-office',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFhirSplatRoute = ApiFhirSplatRouteImport.update({
  id: '/api/fhir/$',
  path: '/api/fhir/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fhir-resources': typeof FhirResourcesRoute
  '/dashboard/front-office': typeof DashboardFrontOfficeRoute
  '/dashboard/physician': typeof DashboardPhysicianRoute
  '/patients/$id': typeof PatientsIdRoute
  '/patients/new': typeof PatientsNewRoute
  '/patients/': typeof PatientsIndexRoute
  '/api/fhir/$': typeof ApiFhirSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fhir-resources': typeof FhirResourcesRoute
  '/dashboard/front-office': typeof DashboardFrontOfficeRoute
  '/dashboard/physician': typeof DashboardPhysicianRoute
  '/patients/$id': typeof PatientsIdRoute
  '/patients/new': typeof PatientsNewRoute
  '/patients': typeof PatientsIndexRoute
  '/api/fhir/$': typeof ApiFhirSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fhir-resources': typeof FhirResourcesRoute
  '/dashboard/front-office': typeof DashboardFrontOfficeRoute
  '/dashboard/physician': typeof DashboardPhysicianRoute
  '/patients/$id': typeof PatientsIdRoute
  '/patients/new': typeof PatientsNewRoute
  '/patients/': typeof PatientsIndexRoute
  '/api/fhir/$': typeof ApiFhirSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fhir-resources'
    | '/dashboard/front-office'
    | '/dashboard/physician'
    | '/patients/$id'
    | '/patients/new'
    | '/patients/'
    | '/api/fhir/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fhir-resources'
    | '/dashboard/front-office'
    | '/dashboard/physician'
    | '/patients/$id'
    | '/patients/new'
    | '/patients'
    | '/api/fhir/$'
  id:
    | '__root__'
    | '/'
    | '/fhir-resources'
    | '/dashboard/front-office'
    | '/dashboard/physician'
    | '/patients/$id'
    | '/patients/new'
    | '/patients/'
    | '/api/fhir/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FhirResourcesRoute: typeof FhirResourcesRoute
  DashboardFrontOfficeRoute: typeof DashboardFrontOfficeRoute
  DashboardPhysicianRoute: typeof DashboardPhysicianRoute
  PatientsIdRoute: typeof PatientsIdRoute
  PatientsNewRoute: typeof PatientsNewRoute
  PatientsIndexRoute: typeof PatientsIndexRoute
  ApiFhirSplatRoute: typeof ApiFhirSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/fhir-resources': {
      id: '/fhir-resources'
      path: '/fhir-resources'
      fullPath: '/fhir-resources'
      preLoaderRoute: typeof FhirResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/': {
      id: '/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof PatientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/new': {
      id: '/patients/new'
      path: '/patients/new'
      fullPath: '/patients/new'
      preLoaderRoute: typeof PatientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$id': {
      id: '/patients/$id'
      path: '/patients/$id'
      fullPath: '/patients/$id'
      preLoaderRoute: typeof PatientsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/physician': {
      id: '/dashboard/physician'
      path: '/dashboard/physician'
      fullPath: '/dashboard/physician'
      preLoaderRoute: typeof DashboardPhysicianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/front-office': {
      id: '/dashboard/front-office'
      path: '/dashboard/front-office'
      fullPath: '/dashboard/front-office'
      preLoaderRoute: typeof DashboardFrontOfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fhir/$': {
      id: '/api/fhir/$'
      path: '/api/fhir/$'
      fullPath: '/api/fhir/$'
      preLoaderRoute: typeof ApiFhirSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FhirResourcesRoute: FhirResourcesRoute,
  DashboardFrontOfficeRoute: DashboardFrontOfficeRoute,
  DashboardPhysicianRoute: DashboardPhysicianRoute,
  PatientsIdRoute: PatientsIdRoute,
  PatientsNewRoute: PatientsNewRoute,
  PatientsIndexRoute: PatientsIndexRoute,
  ApiFhirSplatRoute: ApiFhirSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
